/*const estados = [
    {sigla: 'AC', nome: 'Acre'},
    {sigla: 'AL', nome: ' Alagoas'},
    {sigla: 'AP', nome: ' Amapá'},
    {sigla: 'AM', nome: ' Amazonas'},
    {sigla: 'BA', nome: ' Bahia'},
    {sigla: 'CE', nome: ' Ceará'},
    {sigla: 'DF', nome: ' Distrito Federal'},
    {sigla: 'ES', nome: ' Espírito Santo'},
    {sigla: 'GO', nome: ' Goiás'},
    {sigla: 'MA', nome: ' Maranhão'},
    {sigla: 'MT', nome: ' Mato Grosso'},
    {sigla: 'MS', nome: ' Mato Grosso do Sul'},
    {sigla: 'MG', nome: ' Minas Gerais'},
    {sigla: 'PA', nome: ' Pará'},
    {sigla: 'PB', nome: ' Paraíba '},
    {sigla: 'PR', nome: ' Paraná'},
    {sigla: 'PE', nome: ' Pernambuco'},
    {sigla: 'PI', nome: ' Piauí'},
    {sigla: 'RJ', nome: ' Rio de Janeiro'},
    {sigla: 'RN', nome: ' Rio Grande do Norte'},
    {sigla: 'RS', nome: ' Rio Grande do Sul '},
    {sigla: 'RO', nome: ' Rondônia'},
    {sigla: 'RR', nome: ' Roraima'},
    {sigla: 'SC', nome: ' Santa Catarina '},
    {sigla: 'SP', nome: ' São Paulo '},
    {sigla: 'SE', nome: ' Sergipe'},
    {sigla: 'TO', nome: ' Tocantins'},
];
*/

const estados = [
    {value: 'AC', label: 'Acre'},
    {value: 'AL', label: ' Alagoas'},
    {value: 'AP', label: ' Amapá'},
    {value: 'AM', label: ' Amazonas'},
    {value: 'BA', label: ' Bahia'},
    {value: 'CE', label: ' Ceará'},
    {value: 'DF', label: ' Distrito Federal'},
    {value: 'ES', label: ' Espírito Santo'},
    {value: 'GO', label: ' Goiás'},
    {value: 'MA', label: ' Maranhão'},
    {value: 'MT', label: ' Mato Grosso'},
    {value: 'MS', label: ' Mato Grosso do Sul'},
    {value: 'MG', label: ' Minas Gerais'},
    {value: 'PA', label: ' Pará'},
    {value: 'PB', label: ' Paraíba '},
    {value: 'PR', label: ' Paraná'},
    {value: 'PE', label: ' Pernambuco'},
    {value: 'PI', label: ' Piauí'},
    {value: 'RJ', label: ' Rio de Janeiro'},
    {value: 'RN', label: ' Rio Grande do Norte'},
    {value: 'RS', label: ' Rio Grande do Sul '},
    {value: 'RO', label: ' Rondônia'},
    {value: 'RR', label: ' Roraima'},
    {value: 'SC', label: ' Santa Catarina '},
    {value: 'SP', label: ' São Paulo '},
    {value: 'SE', label: ' Sergipe'},
    {value: 'TO', label: ' Tocantins'},
];


export default estados;
